country_list = [
    "Belgium",
    "Germany",
    "Bulgaria",
    "Japan",
    "China",
    "Malaysia",
    "Ukraine",
    "France",
    "US",
    "Switzerland",
    "United Kingdom",
    "Italy",
    "Spain",
    "Sweden",
    "Netherlands",
    "Global",
    "Turkey",
    "Greece",
    "Serbia",
    "Romania",
    "Russia",
    "Brazil",
    "India",
    "North Macedonia",
    "Europe",
    "North America",
    "Asia",
    "South America",
    "Africa",
    "Oceania",
]

continents_dictionary = {
    "Oceania": [
        "Australia",
        "New Zealand",
        "French Polynesia",
        "New Caledonia",
        "Fiji",
        "Papua New Guinea",
    ],
    "Europe": [
        "Russia",
        "Spain",
        "UK",
        "Italy",
        "Germany",
        "France",
        "Belgium",
        "Belarus",
        "Netherlands",
        "Sweden",
        "Portugal",
        "Switzerland",
        "Ukraine",
        "Poland",
        "Ireland",
        "Romania",
        "Austria",
        "Denmark",
        "Serbia",
        "Czechia",
        "Moldova",
        "Norway",
        "Finland",
        "Luxembourg",
        "Hungary",
        "Greece",
        "North Macedonia",
        "Bulgaria",
        "Bosnia and Herzegovina",
        "Croatia",
        "Estonia",
        "Iceland",
        "Lithuania",
        "Slovakia",
        "Slovenia",
        "Albania",
        "Latvia",
        "Andorra",
        "San Marino",
        "Malta",
        "Channel Islands",
        "Isle of Man",
        "Montenegro",
        "Faeroe Islands",
        "Gibraltar",
        "Monaco",
        "Liechtenstein",
        "Vatican City",
    ],
    "North America": [
        "USA",
        "Mexico",
        "Canada",
        "Dominican Republic",
        "Panama",
        "Honduras",
        "Guatemala",
        "Cuba",
        "El Salvador",
        "Haiti",
        "Nicaragua",
        "Sint Maarten",
        "Guadeloupe",
        "Martinique",
        "Bahamas",
        "Costa Rica",
        "Jamaica",
        "Bermuda",
        "Trinidad and Tobago",
        "Barbados",
        "Aruba",
        "Saint Martin",
        "Antigua and Barbuda",
        "Belize",
        "Cayman Islands",
        "Curaçao",
        "Turks and Caicos",
        "Montserrat",
        "British Virgin Islands",
        "Grenada",
        "Saint Lucia",
        "Dominica",
        "St. Vincent Grenadines",
        "Saint Kitts and Nevis",
        "Greenland",
        "Caribbean Netherlands",
        "St. Barth",
        "Anguilla",
        "Saint Pierre Miquelon",
    ],
    "Asia": [
        "Iran",
        "India",
        "Turkey",
        "China",
        "Pakistan",
        "Indonesia",
        "Philippines",
        "Japan",
        "Bangladesh",
        "Saudi Arabia",
        "Afghanistan",
        "Iraq",
        "Israel",
        "UAE",
        "S. Korea",
        "Kuwait",
        "Armenia",
        "Malaysia",
        "Yemen",
        "Azerbaijan",
        "Oman",
        "Thailand",
        "Kazakhstan",
        "Qatar",
        "Tajikistan",
        "Lebanon",
        "Singapore",
        "Bahrain",
        "Kyrgyzstan",
        "Cyprus",
        "Uzbekistan",
        "Nepal",
        "Georgia",
        "Sri Lanka",
        "Jordan",
        "Maldives",
        "Taiwan",
        "Myanmar",
        "Syria",
        "Hong Kong",
        "Palestine",
        "Brunei",
        "Mongolia",
        "Vietnam",
        "Cambodia",
        "Macao",
        "Timor-Leste",
        "Laos",
        "Bhutan",
    ],
    "South America": [
        "Brazil",
        "Peru",
        "Ecuador",
        "Chile",
        "Colombia",
        "Argentina",
        "Bolivia",
        "Uruguay",
        "Venezuela",
        "Guyana",
        "Paraguay",
        "French Guiana",
        "Suriname",
        "Falkland Islands",
    ],
    "Africa": [
        "Egypt",
        "South Africa",
        "Algeria",
        "Sudan",
        "Nigeria",
        "Cameroon",
        "Morocco",
        "Mali",
        "Kenya",
        "DRC",
        "Somalia",
        "Chad",
        "Niger",
        "Burkina Faso",
        "Mauritania",
        "Tunisia",
        "Sierra Leone",
        "Senegal",
        "Ghana",
        "Ivory Coast",
        "Liberia",
        "Djibouti",
        "Mayotte",
        "Guinea",
        "Congo",
        "Gabon",
        "Tanzania",
        "Ethiopia",
        "Togo",
        "Equatorial Guinea",
        "Guinea-Bissau",
        "Sao Tome and Principe",
        "Mauritius",
        "South Sudan",
        "Madagascar",
        "Zambia",
        "CAR",
        "Cabo Verde",
        "Libya",
        "Zimbabwe",
        "Angola",
        "Malawi",
        "Eswatini",
        "Benin",
        "Mozambique",
        "Rwanda",
        "Comoros",
        "Réunion",
        "Burundi",
        "Botswana",
        "Gambia",
        "Western Sahara",
        "Uganda",
        "Namibia",
        "Eritrea",
        "Seychelles",
        "Lesotho",
    ],
}
